### ISSUE TITLE
Invariant failed: It is not allowed to create or change state outside an `action` when MobX is in strict mode

### ISSUE THREAD

**Issue by jrnewell** [philolo1/OnsenUI-MobX-Todo#1]
your example doesn't seem to run out of the box

```
Uncaught Error: [mobx] Invariant failed: It is not allowed to create or change state outside an `action` when MobX is in strict mode. Wrap the current method in `action` if this state change is intended
```

The error seem to be  due to the fact that you are updating state in the TimerStore constructor with strict mode on.  It looks like it can be fixed by wrapping it with `runInAction`

``` javascript
  constructor() {
    runInAction(() => {
      this.isRunning = false;
      this.timer = new Timer();
      this.laps = [];
    });
  }
```

**Comment by philolo1** [comment]
I think the mobx version changed in the meantime. I will check and merge your pull request. Thanks
